version: '3.7'

services:

  # PHP/Nginx.
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "83:8080"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/php/fpm-pool.conf:/etc/php81/php-fpm.d/www.conf
      - ./docker/php/php.ini:/etc/php81/conf.d/custom.ini
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./docker/crontab:/etc/cron.d/cron

  # PostgreSQL.
  database:
    ports:
      - "54323:5432"
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - db-data:/var/lib/postgresql/data
#      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

  # Redis.
  redis:
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data

  # Mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1028:1025'
      - '8028:8025'
    networks:
      - app-network

# Volumes
volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
