#name: Push workflow.
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    name: Deploy app to production
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout main
#        uses: actions/checkout@main
#
#      - name: Set up QEMU.
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker Buildx.
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to DockerHub.
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Build and push.
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: auburnpixels/the-gear-giveaway:latest
#          file: ./docker/php/Dockerfile
#          build-args: |
#            APP_ENV=production
#
#      - name: Pull docker image and rebuild.
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.DIGITALOCEAN_IP_ADDRESS }}
#          username: ${{ secrets.DIGITALOCEAN_USER }}
#          key: ${{ secrets.DIGITALOCEAN_KEY }}
#          script:
#            cd /var/www/thegeargiveaway.com &&
#            docker pull auburnpixels/the-gear-giveaway &&
#            docker-compose down &&
#            docker image rm auburnpixels/the-gear-giveaway &&
#            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d &&
#            docker-compose exec -T -u nobody app sh post-deploy.sh &&
#            docker rmi $(docker images -f "dangling=true" -q)

---
name: Push workflow.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to `Spin My Workout`
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@137.184.34.132:22/spin-my-workout'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
